import { MigrationInterface, QueryRunner } from "typeorm";

export class AddMissingSellersColumns1763153464515 implements MigrationInterface {
    name = 'AddMissingSellersColumns1763153464515'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_90de4241bbba3c32d065eba1207"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_commission_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_delivered_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pixel_events_sellerId_eventType_createdAt"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_entity"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_timestamp"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_performed_by"`);
        await queryRunner.query(`CREATE TABLE "seller_locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sellerId" uuid NOT NULL, "city" character varying(100) NOT NULL, "state" character varying(100) NOT NULL, "isPrimary" boolean NOT NULL DEFAULT false, "address" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_53ed90d1a4587fbda8737b4228f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "orderId"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "sellerId"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "buyerId"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "taxAmount"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "shippingCost"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "totalAmount"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "billingAddress"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "items"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "issueDate"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "dueDate"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "paidDate"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "invoiceNumber"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "currency"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "pdfUrl"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "before_value"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "after_value"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entity_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "ip_address"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "user_agent"`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "invoiceNumber" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "orderId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "sellerId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "buyerId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "taxAmount" numeric(8,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "shippingCost" numeric(8,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "totalAmount" numeric(15,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "currency" character varying(10) NOT NULL DEFAULT 'USD'`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "billingAddress" json NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "items" json NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "pdfUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "issueDate" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "dueDate" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "paidDate" date`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "platform_config" ADD "updated_by" uuid`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "invoice_number" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "UQ_d8f8d3788694e1b3f96c42c36fb" UNIQUE ("invoice_number")`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "invoice_type" character varying(30) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "order_id" uuid`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "seller_id" uuid`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "buyer_id" uuid`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "issuer_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "issuer_document" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "issuer_address" text`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "recipient_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "recipient_document" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "recipient_address" text`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "vat_amount" numeric(10,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "total_amount" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "issued_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "due_date" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "payment_method" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "cufe" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "dian_response" jsonb`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entityId" uuid`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "changes" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "performedBy" uuid`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "ipAddress" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "userAgent" text`);
        await queryRunner.query(`ALTER TYPE "public"."sellers_documenttype_enum" RENAME TO "sellers_documenttype_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."sellers_documenttype_enum" AS ENUM('CC', 'CE', 'NIT', 'PASSPORT')`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "documentType" TYPE "public"."sellers_documenttype_enum" USING "documentType"::"text"::"public"."sellers_documenttype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sellers_documenttype_enum_old"`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "address" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "city" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "country" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "businessCategory" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "rutVerified" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "comercioVerified" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "bankAccountType"`);
        await queryRunner.query(`CREATE TYPE "public"."sellers_bankaccounttype_enum" AS ENUM('ahorros', 'corriente')`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "bankAccountType" "public"."sellers_bankaccounttype_enum"`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "verificationStatus"`);
        await queryRunner.query(`CREATE TYPE "public"."sellers_verificationstatus_enum" AS ENUM('pending', 'documents_uploaded', 'under_review', 'approved', 'rejected', 'needs_update')`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "verificationStatus" "public"."sellers_verificationstatus_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "verifiedBy"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "verifiedBy" character varying`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "reviewedBy"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "reviewedBy" character varying`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "shippingLocalPrice" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "shippingLocalPrice" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "shippingNationalPrice" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "shippingNationalPrice" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "shippingFreeEnabled" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "platform_fee_rate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "platform_fee_amount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "seller_commission_rate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "seller_commission_amount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "seller_net_amount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "commission_status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "sellerId"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "sellerId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "userId" character varying`);
        await queryRunner.query(`ALTER TYPE "public"."pixel_event_type" RENAME TO "pixel_event_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."pixel_events_eventtype_enum" AS ENUM('page_view', 'product_view', 'add_to_cart', 'purchase', 'custom')`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ALTER COLUMN "eventType" TYPE "public"."pixel_events_eventtype_enum" USING "eventType"::"text"::"public"."pixel_events_eventtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."pixel_event_type_old"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "productId"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "productId" character varying`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "orderId"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "orderId" character varying`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "currency"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "currency" character varying`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "sessionId"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "sessionId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "ipAddress"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "ipAddress" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "userAgent"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "userAgent" character varying`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "referer"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "referer" character varying`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "url"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "url" character varying`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "customData"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "customData" json`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "eventData"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "eventData" json`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "country"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "country" character varying`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "city" character varying`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ALTER COLUMN "strength" SET DEFAULT '0.5'`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ALTER COLUMN "exploreExploitRatio" SET DEFAULT '0.5'`);
        await queryRunner.query(`ALTER TABLE "platform_config" DROP CONSTRAINT "platform_config_key_key"`);
        await queryRunner.query(`ALTER TABLE "platform_config" DROP COLUMN "key"`);
        await queryRunner.query(`ALTER TABLE "platform_config" ADD "key" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "platform_config" ADD CONSTRAINT "UQ_e288d39f7103fdc2a057f96b62e" UNIQUE ("key")`);
        await queryRunner.query(`ALTER TABLE "platform_config" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "platform_config" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "platform_config" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "platform_config" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "subtotal" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "status" character varying(20) NOT NULL DEFAULT 'issued'`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "timestamp" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "timestamp" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "performed_by"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "performed_by" uuid`);
        await queryRunner.query(`CREATE INDEX "IDX_ec681ae8f3c84b0749cb7f3050" ON "pixel_events" ("sellerId", "eventType", "createdAt") `);
        await queryRunner.query(`ALTER TABLE "seller_locations" ADD CONSTRAINT "FK_43cb4c7e96ff15c1fb894c8cf4a" FOREIGN KEY ("sellerId") REFERENCES "sellers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_f0f155dfb8fa26ce22585fa9301" FOREIGN KEY ("commission_invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_4d05da92b8c3173c7f33138208f" FOREIGN KEY ("fee_invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_90de4241bbba3c32d065eba1207" FOREIGN KEY ("buyerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "platform_config" ADD CONSTRAINT "FK_b2b12e88196a0d6ee61a359542c" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_ea83c3b911906a3578de2340fdf" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_44bb811de7d3cef32f28094ea19" FOREIGN KEY ("seller_id") REFERENCES "sellers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_8efb05dbd2ceb9ab8e37c446d1f" FOREIGN KEY ("buyer_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_ae97aac6d6d471b9d88cea1c971" FOREIGN KEY ("performed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_ae97aac6d6d471b9d88cea1c971"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_8efb05dbd2ceb9ab8e37c446d1f"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_44bb811de7d3cef32f28094ea19"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_ea83c3b911906a3578de2340fdf"`);
        await queryRunner.query(`ALTER TABLE "platform_config" DROP CONSTRAINT "FK_b2b12e88196a0d6ee61a359542c"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_90de4241bbba3c32d065eba1207"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_4d05da92b8c3173c7f33138208f"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_f0f155dfb8fa26ce22585fa9301"`);
        await queryRunner.query(`ALTER TABLE "seller_locations" DROP CONSTRAINT "FK_43cb4c7e96ff15c1fb894c8cf4a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ec681ae8f3c84b0749cb7f3050"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "performed_by"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "performed_by" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "timestamp" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "timestamp" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('cancelled', 'draft', 'overdue', 'paid', 'sent')`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "subtotal" TYPE numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "platform_config" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "platform_config" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "platform_config" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "platform_config" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "platform_config" DROP CONSTRAINT "UQ_e288d39f7103fdc2a057f96b62e"`);
        await queryRunner.query(`ALTER TABLE "platform_config" DROP COLUMN "key"`);
        await queryRunner.query(`ALTER TABLE "platform_config" ADD "key" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "platform_config" ADD CONSTRAINT "platform_config_key_key" UNIQUE ("key")`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ALTER COLUMN "exploreExploitRatio" SET DEFAULT 0.5`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ALTER COLUMN "strength" SET DEFAULT 0.5`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "city" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "country"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "country" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "eventData"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "eventData" jsonb`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "customData"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "customData" jsonb`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "url"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "url" text`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "referer"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "referer" text`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "userAgent"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "userAgent" text`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "ipAddress"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "ipAddress" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "sessionId"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "sessionId" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "currency"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "currency" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "orderId"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "orderId" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "productId"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "productId" character varying(255)`);
        await queryRunner.query(`CREATE TYPE "public"."pixel_event_type_old" AS ENUM('add_to_cart', 'custom', 'page_view', 'product_view', 'purchase')`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ALTER COLUMN "eventType" TYPE "public"."pixel_event_type_old" USING "eventType"::"text"::"public"."pixel_event_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."pixel_events_eventtype_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."pixel_event_type_old" RENAME TO "pixel_event_type"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "userId" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "pixel_events" DROP COLUMN "sellerId"`);
        await queryRunner.query(`ALTER TABLE "pixel_events" ADD "sellerId" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "commission_status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "seller_net_amount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "seller_commission_amount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "seller_commission_rate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "platform_fee_amount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "platform_fee_rate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "shippingFreeEnabled" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "shippingNationalPrice" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "shippingNationalPrice" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "shippingLocalPrice" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "shippingLocalPrice" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "reviewedBy"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "reviewedBy" uuid`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "verifiedBy"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "verifiedBy" uuid`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "verificationStatus"`);
        await queryRunner.query(`DROP TYPE "public"."sellers_verificationstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "verificationStatus" character varying`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "bankAccountType"`);
        await queryRunner.query(`DROP TYPE "public"."sellers_bankaccounttype_enum"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "bankAccountType" character varying`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "comercioVerified" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "rutVerified" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "businessCategory" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "country" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "city" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "address" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."sellers_documenttype_enum_old" AS ENUM('CC', 'NIT', 'Passport', 'RUT')`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "documentType" TYPE "public"."sellers_documenttype_enum_old" USING "documentType"::"text"::"public"."sellers_documenttype_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."sellers_documenttype_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."sellers_documenttype_enum_old" RENAME TO "sellers_documenttype_enum"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "userAgent"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "ipAddress"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "performedBy"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "changes"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entityId"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "dian_response"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "cufe"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "payment_method"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "due_date"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "issued_at"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "total_amount"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "vat_amount"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "recipient_address"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "recipient_document"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "recipient_name"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "issuer_address"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "issuer_document"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "issuer_name"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "buyer_id"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "seller_id"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "order_id"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "invoice_type"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "UQ_d8f8d3788694e1b3f96c42c36fb"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "invoice_number"`);
        await queryRunner.query(`ALTER TABLE "platform_config" DROP COLUMN "updated_by"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "paidDate"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "dueDate"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "issueDate"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "pdfUrl"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "items"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "billingAddress"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "currency"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "totalAmount"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "shippingCost"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "taxAmount"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "buyerId"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "sellerId"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "orderId"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "invoiceNumber"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "user_agent" text`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "ip_address" character varying(45)`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entity_id" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "after_value" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "before_value" jsonb`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "pdfUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "currency" character varying(10) NOT NULL DEFAULT 'USD'`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "invoiceNumber" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "paidDate" date`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "dueDate" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "issueDate" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "items" json NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "billingAddress" json NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "totalAmount" numeric(15,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "shippingCost" numeric(8,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "taxAmount" numeric(8,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "buyerId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "sellerId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "orderId" uuid NOT NULL`);
        await queryRunner.query(`DROP TABLE "seller_locations"`);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_performed_by" ON "audit_logs" ("performed_by") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_timestamp" ON "audit_logs" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_entity" ON "audit_logs" ("entity", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_pixel_events_sellerId_eventType_createdAt" ON "pixel_events" ("sellerId", "eventType", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_delivered_at" ON "orders" ("deliveredAt") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_commission_status" ON "orders" ("commission_status") `);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_90de4241bbba3c32d065eba1207" FOREIGN KEY ("buyerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
