import {
  BarChart3,
  Calendar,
  ChevronLeft,
  ChevronRight,
  Copy,
  CreditCard,
  DollarSign,
  Download,
  Eye,
  Heart,
  Home,
  Loader2,
  LogOut,
  Menu,
  MoreVertical,
  Package,
  Play,
  Plus,
  Radio,
  Settings,
  Share,
  TrendingUp,
  Upload,
  User,
  Users,
  Video,
  X,
  type LucideIcon,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  home: Home,
  video: Video,
  radio: Radio,
  barChart: BarChart3,
  dollarSign: DollarSign,
  user: User,
  users: Users,
  menu: Menu,
  settings: Settings,
  logOut: LogOut,
  plus: Plus,
  upload: Upload,
  play: Play,
  eye: Eye,
  heart: Heart,
  share: Share,
  trendingUp: TrendingUp,
  calendar: Calendar,
  package: Package,
  creditCard: CreditCard,
  download: Download,
  copy: Copy,
  moreVertical: MoreVertical,
  x: X,
}