import { ApiProperty } from '@nestjs/swagger';

export class TopProductDto {
  @ApiProperty({
    description: 'Product ID',
    example: 'product_123',
  })
  id: string;

  @ApiProperty({
    description: 'Product name',
    example: 'iPhone 15 Pro Max',
  })
  name: string;

  @ApiProperty({
    description: 'Product images',
    type: [String],
    example: ['https://example.com/image1.jpg'],
  })
  images: string[];

  @ApiProperty({
    description: 'Number of orders containing this product',
    example: 142,
  })
  ordersCount: number;

  @ApiProperty({
    description: 'Number of product views from pixel events',
    example: 2847,
  })
  viewsCount: number;

  @ApiProperty({
    description: 'Average review rating',
    example: 4.8,
  })
  rating: number;

  @ApiProperty({
    description: 'Total revenue generated by this product',
    example: 284799.99,
  })
  totalRevenue: number;

  @ApiProperty({
    description: 'Product price',
    example: 1999.99,
  })
  price: number;

  @ApiProperty({
    description: 'Product slug',
    example: 'iphone-15-pro-max',
  })
  slug: string;
}
